#!/bin/bash
BASE_DIR="/Users/NOTME"
main()
{
for FILE in $(ls ${BASE_DIR}/.cheat/)
do
        MATCH=$(head -n1 ${BASE_DIR}/.cheat/$FILE |grep -c $KEYWORD)
        if [ ! $MATCH == "0" ]
        then
                cat ${BASE_DIR}/.cheat/$FILE
        fi
done
}

usage()
{
echo "cheat [KEYWORD]"
exit 1
}

KEYWORD=$1

if [ ! -z $KEYWORD ]
then
        main
else
        echo "Please choose one of the following categories:"
        ls -l ${BASE_DIR}/.cheat/
        echo
        usage
fi
